apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: projet-pma
  labels:
    app: mysql
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
